import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1780769378062 implements MigrationInterface {
    name = 'InitialSchema1780769378062'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('active', 'completed', 'archived')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "clientName" character varying NOT NULL, "tenderRef" character varying, "status" "public"."projects_status_enum" NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "examCode" character varying NOT NULL, "name" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "projectId" uuid NOT NULL, CONSTRAINT "UQ_5803a6978e0933d4322ce935c45" UNIQUE ("examCode", "projectId"), CONSTRAINT "PK_b43159ee3efa440952794b4f53e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "examId" uuid, CONSTRAINT "UQ_84233f9dcf45f4d75a90b26f274" UNIQUE ("name", "examId"), CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "centers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "centerCode" character varying NOT NULL, "name" character varying NOT NULL, "address" character varying NOT NULL, "city" character varying NOT NULL, "state" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "projectId" uuid NOT NULL, CONSTRAINT "UQ_d76ad0328140a0e76e3e0f1ca5f" UNIQUE ("centerCode", "projectId"), CONSTRAINT "PK_692e2318139b8148445f33c2880" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."field_operators_idprooftype_enum" AS ENUM('aadhaar', 'pan', 'other')`);
        await queryRunner.query(`CREATE TABLE "field_operators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "phone" character varying NOT NULL, "phoneValid" boolean NOT NULL DEFAULT false, "phoneValidationData" jsonb, "selfieUrl" character varying, "idProofType" "public"."field_operators_idprooftype_enum" NOT NULL, "idProofUrl" character varying, "isActive" boolean NOT NULL DEFAULT true, "sessionTokenHash" character varying, "lastLoginAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0c89b0e5d85509ab94cef049fe0" UNIQUE ("phone"), CONSTRAINT "PK_931ad75009dddbc321c160d5575" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_341a981a5110e80a6be32a3bb4" ON "field_operators"  ("lastLoginAt") `);
        await queryRunner.query(`CREATE TYPE "public"."devices_status_enum" AS ENUM('pending', 'active', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deviceCode" character varying NOT NULL, "serialNumber" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, "locked" boolean NOT NULL DEFAULT false, "status" "public"."devices_status_enum" NOT NULL DEFAULT 'pending', "activationSecretHash" character varying, "deviceTokenHash" character varying, "activatedAt" TIMESTAMP, "lastSeenAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "centerId" uuid, "activatedById" uuid, CONSTRAINT "UQ_fc23b3ead43da6f88e88b0150f4" UNIQUE ("deviceCode"), CONSTRAINT "PK_b1514758245c12daf43486dd1f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c37da3607f7214c3dda1803d09" ON "devices"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f898d01eec972a9bc4fbef3e4" ON "devices"  ("lastSeenAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_84ed928d95f4061aae28b6bd76" ON "devices"  ("activatedById") `);
        await queryRunner.query(`CREATE TYPE "public"."offline_sync_jobs_status_enum" AS ENUM('downloaded', 'uploaded')`);
        await queryRunner.query(`CREATE TABLE "offline_sync_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."offline_sync_jobs_status_enum" NOT NULL DEFAULT 'downloaded', "candidateCount" integer NOT NULL DEFAULT '0', "uploadedAt" TIMESTAMP WITH TIME ZONE, "uploadedCount" integer NOT NULL DEFAULT '0', "conflictCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deviceId" uuid NOT NULL, "examId" uuid NOT NULL, "shiftId" uuid, "centerId" uuid NOT NULL, CONSTRAINT "PK_6d97c23685fdc1a389194432291" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0f47ed00cc11e26d433e984396" ON "offline_sync_jobs"  ("deviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f06566fc5c5ef45b1dcd66abf" ON "offline_sync_jobs"  ("examId") `);
        await queryRunner.query(`CREATE INDEX "IDX_060d6767401155bfa26cbe424a" ON "offline_sync_jobs"  ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."biometric_captures_type_enum" AS ENUM('enrollment', 'verification')`);
        await queryRunner.query(`CREATE TABLE "biometric_captures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."biometric_captures_type_enum" NOT NULL, "faceUrl" character varying, "fingerprintTemplate" text, "irisTemplate" text, "matchScore" double precision, "isManualOverride" boolean NOT NULL DEFAULT false, "overrideReason" character varying, "overriddenByUserId" character varying, "capturedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "personIdentityId" uuid NOT NULL, "candidateId" uuid NOT NULL, "fieldOperatorId" uuid, "deviceId" uuid, "syncJobId" uuid, CONSTRAINT "PK_d0bb33544f7d890b410ad2de3d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1eee9029605088fd7bc414ffe" ON "biometric_captures"  ("personIdentityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb9b62dad128d46f406c2cbf8c" ON "biometric_captures"  ("candidateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f171408f4575050237fc89027" ON "biometric_captures"  ("fieldOperatorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa7c37492fe85edbdd56fbacc5" ON "biometric_captures"  ("capturedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f07661d7ba4eaf8724aa1aea9" ON "biometric_captures"  ("syncJobId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eec01a3e30bd031bb6f805d0bd" ON "biometric_captures"  ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_201fc633c5f28d49fe52d564ac" ON "biometric_captures"  ("type", "matchScore", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c913fb6aea806605f49a531a20" ON "biometric_captures"  ("candidateId", "type", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ffcb3a6fff11c7f1f1c7f47055" ON "biometric_captures"  ("fieldOperatorId", "type", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."biometric_device_models_modality_enum" AS ENUM('FINGERPRINT', 'IRIS', 'FACE')`);
        await queryRunner.query(`CREATE TABLE "biometric_device_models" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "manufacturer" character varying NOT NULL, "model" character varying NOT NULL, "modality" "public"."biometric_device_models_modality_enum" NOT NULL, "supportedTemplateFormats" jsonb, "sdkName" character varying, "sdkVersion" character varying, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_08c999e3c166ea47c51861b779f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."biometric_templates_modality_enum" AS ENUM('FINGERPRINT', 'IRIS', 'FACE')`);
        await queryRunner.query(`CREATE TYPE "public"."biometric_templates_position_enum" AS ENUM('RIGHT_THUMB', 'LEFT_THUMB', 'RIGHT_INDEX', 'LEFT_INDEX', 'LEFT_EYE', 'RIGHT_EYE')`);
        await queryRunner.query(`CREATE TYPE "public"."biometric_templates_templateformat_enum" AS ENUM('ISO_19794_2', 'ISO_19794_6', 'VENDOR_SPECIFIC')`);
        await queryRunner.query(`CREATE TABLE "biometric_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "modality" "public"."biometric_templates_modality_enum" NOT NULL, "position" "public"."biometric_templates_position_enum", "templateFormat" "public"."biometric_templates_templateformat_enum" NOT NULL, "templateData" text NOT NULL, "qualityScore" double precision, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "personIdentityId" uuid NOT NULL, "capturedDeviceModelId" uuid, CONSTRAINT "PK_79d26cec11f276889d94a8d0909" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1d52f43bcd0d6128d4fa8a55f7" ON "biometric_templates"  ("templateFormat") `);
        await queryRunner.query(`CREATE INDEX "IDX_389be3d9c0b3282e8aef0ec18a" ON "biometric_templates"  ("capturedDeviceModelId") `);
        await queryRunner.query(`CREATE INDEX "idx_bt_modality_position" ON "biometric_templates"  ("modality", "position") `);
        await queryRunner.query(`CREATE INDEX "idx_bt_identity_modality" ON "biometric_templates"  ("personIdentityId", "modality") `);
        await queryRunner.query(`CREATE TABLE "person_identities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "primaryPhotoUrl" character varying, "fingerprintTemplate" text, "irisTemplate" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d558a4dfa3f67d93afb121ba202" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "candidates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rollNumber" character varying NOT NULL, "name" character varying NOT NULL, "photoUrl" character varying, "verified" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "examId" uuid, "shiftId" uuid, "centerId" uuid, "personIdentityId" uuid, CONSTRAINT "UQ_8e8e3742bc4b7b3db27a92c1920" UNIQUE ("rollNumber", "examId"), CONSTRAINT "PK_140681296bf033ab1eb95288abb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3617fbac2c1ddbc93d04752670" ON "candidates"  ("examId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9370cbb407f7c8d3d13e79399" ON "candidates"  ("centerId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('master_admin', 'admin', 'operator')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'operator', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "operators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeCode" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "centerId" uuid, CONSTRAINT "UQ_d712f8a7e2142d23d6650fc40d0" UNIQUE ("employeeCode"), CONSTRAINT "REL_aba2e4502865254b0edaedfecd" UNIQUE ("userId"), CONSTRAINT "PK_3d02b3692836893720335a79d1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "verified" boolean NOT NULL DEFAULT true, "remarks" character varying, "verifiedAt" TIMESTAMP NOT NULL DEFAULT now(), "candidateId" uuid, "operatorId" uuid, "deviceId" uuid, CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "action" character varying NOT NULL, "details" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."import_jobs_status_enum" AS ENUM('queued', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "import_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."import_jobs_status_enum" NOT NULL DEFAULT 'queued', "filePath" character varying NOT NULL, "totalRows" integer, "processedRows" integer NOT NULL DEFAULT '0', "createdCount" integer NOT NULL DEFAULT '0', "skippedCount" integer NOT NULL DEFAULT '0', "failedCount" integer NOT NULL DEFAULT '0', "errors" jsonb, "startedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "projectId" uuid NOT NULL, CONSTRAINT "PK_4d206c602f173f98e4bb85819a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "biometric_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requiredFingerprints" jsonb NOT NULL, "requiredIris" jsonb NOT NULL, "allowExtraCapture" boolean NOT NULL DEFAULT true, "minimumFingerprintsRequired" integer NOT NULL DEFAULT '1', "minimumIrisRequired" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "projectId" uuid NOT NULL, CONSTRAINT "REL_732fd14d8295ce64788e19d3ff" UNIQUE ("projectId"), CONSTRAINT "PK_4dceba98aaa6b180a48d675689f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "exams" ADD CONSTRAINT "FK_74575921700b6a03af6378d60ce" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_6d04ac5759d9f551260acc37d69" FOREIGN KEY ("examId") REFERENCES "exams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "centers" ADD CONSTRAINT "FK_509d89aea5885ada5b65b071601" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "FK_90f7e629830698fcc0541af2359" FOREIGN KEY ("centerId") REFERENCES "centers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "FK_84ed928d95f4061aae28b6bd764" FOREIGN KEY ("activatedById") REFERENCES "field_operators"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offline_sync_jobs" ADD CONSTRAINT "FK_0f47ed00cc11e26d433e9843968" FOREIGN KEY ("deviceId") REFERENCES "devices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offline_sync_jobs" ADD CONSTRAINT "FK_5f06566fc5c5ef45b1dcd66abf8" FOREIGN KEY ("examId") REFERENCES "exams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offline_sync_jobs" ADD CONSTRAINT "FK_5f8ef662e8dbabd7e47072f8c29" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offline_sync_jobs" ADD CONSTRAINT "FK_79c3093a260ec89fe5cdf6b6dc9" FOREIGN KEY ("centerId") REFERENCES "centers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biometric_captures" ADD CONSTRAINT "FK_f1eee9029605088fd7bc414ffea" FOREIGN KEY ("personIdentityId") REFERENCES "person_identities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biometric_captures" ADD CONSTRAINT "FK_cb9b62dad128d46f406c2cbf8c3" FOREIGN KEY ("candidateId") REFERENCES "candidates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biometric_captures" ADD CONSTRAINT "FK_0f171408f4575050237fc890275" FOREIGN KEY ("fieldOperatorId") REFERENCES "field_operators"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biometric_captures" ADD CONSTRAINT "FK_81e6e65a0779eb3f6adff3141c1" FOREIGN KEY ("deviceId") REFERENCES "devices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biometric_captures" ADD CONSTRAINT "FK_3f07661d7ba4eaf8724aa1aea98" FOREIGN KEY ("syncJobId") REFERENCES "offline_sync_jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biometric_templates" ADD CONSTRAINT "FK_1291024b8185519aefbc8f17041" FOREIGN KEY ("personIdentityId") REFERENCES "person_identities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biometric_templates" ADD CONSTRAINT "FK_389be3d9c0b3282e8aef0ec18af" FOREIGN KEY ("capturedDeviceModelId") REFERENCES "biometric_device_models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidates" ADD CONSTRAINT "FK_3617fbac2c1ddbc93d04752670d" FOREIGN KEY ("examId") REFERENCES "exams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidates" ADD CONSTRAINT "FK_b20d38731616d2c8c90f414298b" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidates" ADD CONSTRAINT "FK_a9370cbb407f7c8d3d13e793991" FOREIGN KEY ("centerId") REFERENCES "centers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidates" ADD CONSTRAINT "FK_3e3903b2c8d2299f9b3025c35f5" FOREIGN KEY ("personIdentityId") REFERENCES "person_identities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "operators" ADD CONSTRAINT "FK_aba2e4502865254b0edaedfecd2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "operators" ADD CONSTRAINT "FK_25d330ece5d42aea64720a7e3de" FOREIGN KEY ("centerId") REFERENCES "centers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_7094b5cfe304f99bc3b732fcbba" FOREIGN KEY ("candidateId") REFERENCES "candidates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_df68c070ab73b6dbd66386f4c9a" FOREIGN KEY ("operatorId") REFERENCES "operators"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_96c42cd073a10b6e6ce9149ee2d" FOREIGN KEY ("deviceId") REFERENCES "devices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_jobs" ADD CONSTRAINT "FK_1678283d57b49fdd63d19a09c75" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biometric_policies" ADD CONSTRAINT "FK_732fd14d8295ce64788e19d3ff9" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "biometric_policies" DROP CONSTRAINT "FK_732fd14d8295ce64788e19d3ff9"`);
        await queryRunner.query(`ALTER TABLE "import_jobs" DROP CONSTRAINT "FK_1678283d57b49fdd63d19a09c75"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_96c42cd073a10b6e6ce9149ee2d"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_df68c070ab73b6dbd66386f4c9a"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_7094b5cfe304f99bc3b732fcbba"`);
        await queryRunner.query(`ALTER TABLE "operators" DROP CONSTRAINT "FK_25d330ece5d42aea64720a7e3de"`);
        await queryRunner.query(`ALTER TABLE "operators" DROP CONSTRAINT "FK_aba2e4502865254b0edaedfecd2"`);
        await queryRunner.query(`ALTER TABLE "candidates" DROP CONSTRAINT "FK_3e3903b2c8d2299f9b3025c35f5"`);
        await queryRunner.query(`ALTER TABLE "candidates" DROP CONSTRAINT "FK_a9370cbb407f7c8d3d13e793991"`);
        await queryRunner.query(`ALTER TABLE "candidates" DROP CONSTRAINT "FK_b20d38731616d2c8c90f414298b"`);
        await queryRunner.query(`ALTER TABLE "candidates" DROP CONSTRAINT "FK_3617fbac2c1ddbc93d04752670d"`);
        await queryRunner.query(`ALTER TABLE "biometric_templates" DROP CONSTRAINT "FK_389be3d9c0b3282e8aef0ec18af"`);
        await queryRunner.query(`ALTER TABLE "biometric_templates" DROP CONSTRAINT "FK_1291024b8185519aefbc8f17041"`);
        await queryRunner.query(`ALTER TABLE "biometric_captures" DROP CONSTRAINT "FK_3f07661d7ba4eaf8724aa1aea98"`);
        await queryRunner.query(`ALTER TABLE "biometric_captures" DROP CONSTRAINT "FK_81e6e65a0779eb3f6adff3141c1"`);
        await queryRunner.query(`ALTER TABLE "biometric_captures" DROP CONSTRAINT "FK_0f171408f4575050237fc890275"`);
        await queryRunner.query(`ALTER TABLE "biometric_captures" DROP CONSTRAINT "FK_cb9b62dad128d46f406c2cbf8c3"`);
        await queryRunner.query(`ALTER TABLE "biometric_captures" DROP CONSTRAINT "FK_f1eee9029605088fd7bc414ffea"`);
        await queryRunner.query(`ALTER TABLE "offline_sync_jobs" DROP CONSTRAINT "FK_79c3093a260ec89fe5cdf6b6dc9"`);
        await queryRunner.query(`ALTER TABLE "offline_sync_jobs" DROP CONSTRAINT "FK_5f8ef662e8dbabd7e47072f8c29"`);
        await queryRunner.query(`ALTER TABLE "offline_sync_jobs" DROP CONSTRAINT "FK_5f06566fc5c5ef45b1dcd66abf8"`);
        await queryRunner.query(`ALTER TABLE "offline_sync_jobs" DROP CONSTRAINT "FK_0f47ed00cc11e26d433e9843968"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "FK_84ed928d95f4061aae28b6bd764"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "FK_90f7e629830698fcc0541af2359"`);
        await queryRunner.query(`ALTER TABLE "centers" DROP CONSTRAINT "FK_509d89aea5885ada5b65b071601"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_6d04ac5759d9f551260acc37d69"`);
        await queryRunner.query(`ALTER TABLE "exams" DROP CONSTRAINT "FK_74575921700b6a03af6378d60ce"`);
        await queryRunner.query(`DROP TABLE "biometric_policies"`);
        await queryRunner.query(`DROP TABLE "import_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."import_jobs_status_enum"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TABLE "operators"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9370cbb407f7c8d3d13e79399"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3617fbac2c1ddbc93d04752670"`);
        await queryRunner.query(`DROP TABLE "candidates"`);
        await queryRunner.query(`DROP TABLE "person_identities"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bt_identity_modality"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bt_modality_position"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_389be3d9c0b3282e8aef0ec18a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d52f43bcd0d6128d4fa8a55f7"`);
        await queryRunner.query(`DROP TABLE "biometric_templates"`);
        await queryRunner.query(`DROP TYPE "public"."biometric_templates_templateformat_enum"`);
        await queryRunner.query(`DROP TYPE "public"."biometric_templates_position_enum"`);
        await queryRunner.query(`DROP TYPE "public"."biometric_templates_modality_enum"`);
        await queryRunner.query(`DROP TABLE "biometric_device_models"`);
        await queryRunner.query(`DROP TYPE "public"."biometric_device_models_modality_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffcb3a6fff11c7f1f1c7f47055"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c913fb6aea806605f49a531a20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_201fc633c5f28d49fe52d564ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eec01a3e30bd031bb6f805d0bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f07661d7ba4eaf8724aa1aea9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa7c37492fe85edbdd56fbacc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f171408f4575050237fc89027"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb9b62dad128d46f406c2cbf8c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1eee9029605088fd7bc414ffe"`);
        await queryRunner.query(`DROP TABLE "biometric_captures"`);
        await queryRunner.query(`DROP TYPE "public"."biometric_captures_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_060d6767401155bfa26cbe424a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f06566fc5c5ef45b1dcd66abf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f47ed00cc11e26d433e984396"`);
        await queryRunner.query(`DROP TABLE "offline_sync_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."offline_sync_jobs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84ed928d95f4061aae28b6bd76"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f898d01eec972a9bc4fbef3e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c37da3607f7214c3dda1803d09"`);
        await queryRunner.query(`DROP TABLE "devices"`);
        await queryRunner.query(`DROP TYPE "public"."devices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_341a981a5110e80a6be32a3bb4"`);
        await queryRunner.query(`DROP TABLE "field_operators"`);
        await queryRunner.query(`DROP TYPE "public"."field_operators_idprooftype_enum"`);
        await queryRunner.query(`DROP TABLE "centers"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TABLE "exams"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
    }

}
